# Generated by Django 2.2 on 2019-07-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0002_auto_20190524_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='certificacion',
            field=models.CharField(choices=[('Ecológico', 'Ecológico'), ('Kilómetro cero', 'Kilómetro cero')], max_length=5, verbose_name='Certificación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Verduras', 'Verduras'), ('Frutas', 'Frutas'), ('Panadería y bollería', 'Panadería y bollería'), ('Legumbres', 'Legumbres'), ('Pastas y arroces', 'Pastas y arroces'), ('Harinas, cereales y semillas', 'Harinas, cereales y semillas'), ('Frutos secos y deshidratados', 'Frutos secos y deshidratados'), ('Lácteos, yogures y huevos', 'Lácteos, yogures y huevos'), ('Aceites, condimentos y sal', 'Aceites, condimentos y sal'), ('Azúcar y miel', 'Azúcar y miel'), ('Conservas y mermeladas', 'Conservas y mermeladas'), ('Zumos, cafés y bebidas', 'Zumos, cafés y bebidas'), ('Infusiones, tés y aromáticas', 'Infusiones, tés y aromáticas'), ('Vinos, cervezas y licores', 'Vinos, cervezas y licores'), ('Chocolate, aperitivos y dulces', 'Chocolate, aperitivos y dulces'), ('Higiene personal', 'Higiene personal'), ('Productos de limpieza', 'Productos de limpieza'), ('Alimentación infantil', 'Alimentación infantil'), ('Ropa y textil', 'Ropa y textil')], max_length=30, verbose_name='Tipo de producto'),
        ),
    ]
