# Generated by Django 2.2 on 2019-07-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0003_auto_20190717_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='Sí', max_length=2, verbose_name='Stock'),
        ),
    ]
