# Generated by Django 2.2 on 2019-07-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0004_auto_20190717_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='certificacion',
            field=models.CharField(choices=[('Ecológico', 'Ecológico'), ('Kilómetro cero', 'Kilómetro cero')], max_length=15, verbose_name='Certificación'),
        ),
    ]
