# Generated by Django 2.2 on 2019-07-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0005_auto_20190718_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='nombreEmpresa',
            field=models.CharField(default='company', max_length=50, verbose_name='Nombre de empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formacobro',
            name='tipoCobro',
            field=models.CharField(choices=[('Tarjeta de crédito', 'Tarjeta de crédito'), ('Contra-reembolso', 'Contra-reembolso'), ('Efectivo', 'Efectivo')], max_length=20, verbose_name='Tipo de cobro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='Nombre'),
        ),
    ]
