# Generated by Django 2.2 on 2019-07-19 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0006_auto_20190719_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioUnidad',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Precio'),
        ),
    ]
