# Generated by Django 2.2 on 2019-07-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0007_auto_20190719_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacobro',
            name='tipoCobro',
            field=models.TextField(max_length=200, verbose_name='Tipo de cobro'),
        ),
    ]
