# Generated by Django 2.2 on 2019-07-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0009_auto_20190729_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseñaproductor',
            name='calificacion',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='1', max_length=1, verbose_name='Calificación'),
        ),
    ]
