# Generated by Django 2.2 on 2019-07-31 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0012_auto_20190731_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseñaproductor',
            name='consumidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñasConsumidor', to='mvp.Consumidor'),
        ),
        migrations.AlterField(
            model_name='reseñaproductor',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñasProductor', to='mvp.Productor'),
        ),
    ]
