# Generated by Django 2.2 on 2019-08-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0013_auto_20190731_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='articulo',
            field=models.TextField(help_text='Escriba el artículo', max_length=5000, verbose_name='Artículo'),
        ),
    ]
