# Generated by Django 2.2 on 2019-08-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0015_auto_20190801_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseñaproducto',
            name='calificacion',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='1', max_length=1, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='reseñaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñasProducto', to='mvp.Producto'),
        ),
    ]
