# Generated by Django 2.2 on 2019-08-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0016_auto_20190805_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='Leído'),
        ),
    ]
