# Generated by Django 2.2 on 2019-08-10 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0017_mensajeria_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporecogida',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiporecogida', to='mvp.Productor'),
        ),
        migrations.CreateModel(
            name='Geolocalizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geolocalizacion', to='mvp.Productor')),
            ],
        ),
    ]
