# Generated by Django 2.2 on 2019-08-13 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0018_auto_20190810_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total')),
                ('producto', models.ManyToManyField(blank=True, null=True, to='mvp.Producto')),
            ],
        ),
    ]
