# Generated by Django 2.2 on 2019-08-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0020_auto_20190813_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='producto',
            new_name='productos',
        ),
    ]
