# Generated by Django 2.2 on 2019-08-14 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0021_auto_20190813_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemCarro', to='mvp.Producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='lineaenvio',
            name='lineaProducto',
        ),
        migrations.DeleteModel(
            name='LineaProducto',
        ),
        migrations.AddField(
            model_name='carrito',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='mvp.ItemCarrito'),
        ),
    ]
