# Generated by Django 2.2 on 2019-08-14 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0023_auto_20190814_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='precioTotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='PrecioTotal'),
        ),
    ]
