# Generated by Django 2.2 on 2019-08-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0025_auto_20190816_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numeroPedido',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
