# Generated by Django 2.2 on 2019-08-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0026_auto_20190816_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='consumidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidosConsumidor', to='mvp.Consumidor'),
        ),
    ]
