# Generated by Django 2.2 on 2019-08-19 18:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0029_auto_20190819_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacobro',
            name='tipoCobro',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de credito', 'Tarjeta de crédito'), ('Contra reembolso', 'Contra reembolso')], max_length=20),
        ),
    ]
