# Generated by Django 2.2 on 2019-08-19 19:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0030_auto_20190819_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacobro',
            name='tipoCobro',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de credito', 'Tarjeta de crédito'), ('Contra reembolso', 'Contra reembolso')], max_length=60),
        ),
    ]
