# Generated by Django 2.2 on 2019-08-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0032_auto_20190822_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoaproductor',
            name='itemCarrito',
        ),
    ]
