# Generated by Django 2.2 on 2019-08-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0034_itemcarrito_productor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('EnProceso', 'En proceso'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='EnProceso', max_length=20, verbose_name='Estado del pedido'),
        ),
    ]
