# Generated by Django 2.2 on 2019-08-25 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0036_auto_20190824_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoaproductor',
            name='fechaHora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha y hora'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DireccionEnvio',
        ),
    ]
