# Generated by Django 2.2 on 2019-08-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0037_auto_20190825_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoReparto',
        ),
    ]
