# Generated by Django 2.2 on 2019-08-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0038_delete_tiporeparto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('EnProceso', 'En proceso'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado'), ('Listo', 'Listo para recoger'), ('Entregado', 'Entregado')], default='EnProceso', max_length=20, verbose_name='Estado del pedido'),
        ),
    ]
