# Generated by Django 2.2 on 2019-08-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0040_auto_20190827_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoaproductor',
            name='visto',
            field=models.BooleanField(default=False, verbose_name='Visto'),
        ),
    ]
