# Generated by Django 2.2 on 2019-08-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0041_pedidoaproductor_visto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pago',
            name='consumidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mvp.Consumidor'),
        ),
    ]
