# Generated by Django 2.2 on 2019-08-27 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0045_auto_20190827_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='precio',
            new_name='precioTotal',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='pagado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='payer_email',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='payer_id',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='pago',
            name='consumidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mvp.Consumidor'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fechaHora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha y hora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='paypalId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mvp.Pedido'),
        ),
    ]
